export const CHECK_OPEN_ID = '/checkOpenId'
export const GET_TYPE_INFO = '/getTypeInfo'
export const ADD_ARTICLE = '/addArticle'
export const UPDATE_ARTICLE = '/updateArticle'
export const GET_ARTICLE_LIST = '/getArticleList'
export const DEL_ARTICLE = '/delArticle/'
export const GET_ARTICLE_BY_ID = '/getArticleById/'
